import { AthleteType } from "../types/athlete";

export const stateMultipliers: Record<string, number> = {
  "California": 1.5,
  "New York": 1.5,
  "Texas": 1.5,
  "Florida": 1.4,
  "Illinois": 1.4,
  "Pennsylvania": 1.4,
  "Georgia": 1.3,
  "Ohio": 1.3,
  "North Carolina": 1.3,
  "Michigan": 1.3,
  "Washington": 1.3,
  "Virginia": 1.2,
  "Massachusetts": 1.2,
  "Arizona": 1.2,
  "Missouri": 1.2,
  "Tennessee": 1.2,
  "Minnesota": 1.2,
  "Indiana": 1.2,
  "Colorado": 1.2,
  "Maryland": 1.2,
  "Wisconsin": 1.1,
  "South Carolina": 1.1,
  "Alabama": 1.1,
  "Kentucky": 1.1,
  "Louisiana": 1.1,
  "Oregon": 1.1,
  "Oklahoma": 1.1,
  "Connecticut": 1.1,
  "Iowa": 1.1,
  "Utah": 1.1,
  "Nevada": 1.1,
  "Arkansas": 1.0,
  "Mississippi": 1.0,
  "Kansas": 1.0,
  "New Mexico": 1.0,
  "Nebraska": 1.0,
  "West Virginia": 1.0,
  "Idaho": 1.0,
  "Hawaii": 1.0,
  "Maine": 1.0,
  "New Hampshire": 1.0,
  "Montana": 1.0,
  "Rhode Island": 1.0,
  "Delaware": 1.0,
  "South Dakota": 1.0,
  "North Dakota": 1.0,
  "Alaska": 1.0,
  "Vermont": 1.0,
  "Wyoming": 1.0
};



export const sportMultipliers: Record<string, number> = {
  'Football': 3.0,
  'Basketball': 2.0,
  'Baseball': 1.2,
  'Softball': 1.1,
  'Volleyball': 1.0,
  'Gymnastics': 0.9,
  'Soccer': 0.9,
  'Lacrosse': 0.8,
  'Wrestling': 0.8,
  'Track and Field': 0.7,
  'Swimming and Diving': 0.6,
  'Cheerleading': 0.6,
  'Dance Team': 0.6,
  'Tennis': 0.6,
  'Golf': 0.6,
  'Rugby': 0.5,
  'Field Hockey': 0.5,
  'Water Polo': 0.5,
  'Esports': 0.5, // Highly variable based on game and player fame
  'Cross Country': 0.4,
  'Rowing': 0.4,
  'Bowling': 0.3,
  'Skiing': 0.3,
  'Powerlifting': 0.3,
  'Surfing': 0.3,
  'Rifle': 0.2,
  'Squash': 0.2,
};


export const athleteMultipliers: Record<AthleteType, number> = {
"Youth": 0.5,
"College": 1.0,
"Pro": 1.5,
};


export const platformMultipliers: Record<string, number> = {
'Instagram': 1.5,
'TikTok': 2.0,
'X': 1.0, 
'YouTube': 1.8,
'Facebook': 0.8,
};